/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface OptimizationConfig {
  batchSize: number
  windowSize: number
  semanticMode: boolean
}
export interface OptimizationStats {
  originalCount: number
  optimizedCount: number
  savingsPercent: number
}
export interface BatchResult {
  batchId: string
  optimizedRequests: Array<string>
  stats: OptimizationStats
}
export declare class TokenOptimizer {
  constructor(batchSize: number, windowSize: number, semanticMode: boolean)
  optimizeText(text: string): OptimizationStats
  optimizeBatch(requests: Array<string>): BatchResult
  addAbbreviation(full: string, abbr: string): void
  addStopWord(word: string): void
}
